language: crystal
dist: xenial
sudo: false

crystal:
  - "0.33.0"
  - nightly

install: shards install

script:
  - crystal spec

matrix:
  fast_finish: true
  allow_failures:
    - crystal: nightly

cache:
  directories:
    - lib
